name: pydem
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.12
  - pip
  - pip:
      - numpy
      - numba
      - matplotlib
      - ipykernel
      - scipy
      - open3d
      - pyglet
      - pyvista
      - trimesh[easy]
      - pyembree