name: pydem
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy
  - numba
  - matplotlib
  - pip:
      - scipy
      - open3d
      - pyglet
      - pyvista
      - trimesh[easy]
      - pyembree

